# Generated by Django 3.1.7 on 2021-03-04 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='relationship',
            new_name='phone',
        ),
    ]
