# Generated by Django 3.1.7 on 2021-03-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactApp', '0003_contact_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
